package com.company.presentation;

public enum MenuOptions {
    SELECT_COMPOSITOR,
    SELECT_CONDUCTOR,
    MANAGE_TRIALS,
    MANAGE_EDITIONS,
    CREATE_TRIALS,
    LIST_TRIALS,
    DELETE_TRIALS,
    EXIT,
    CREATE_EDITION,
    LIST_EDITIONS,
    DUPLICATE_EDITION,
    DELETE_EDITION,
}

